name: Pull Request
on:
  workflow_call:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint pull request title
        uses: ./commitlint
        with:
          message: ${{ github.event.pull_request.title }}

      - name: Lint commit messages
        if: always()
        uses: ./commitlint
        with:
          relaxed: ${{ contains(job.status, 'success') }}
