name: Trigger reusable workflow
on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

jobs:
  commitlint:
    uses: ostsmolynets/test-reusable-workflows/.github/workflows/common-commitlint.yml@master
