name: Pull Request
on:
  workflow_dispatch:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint pull request
        uses: ostsmolynets/test-reusable-workflows/.github/workflows/common-commitlint.yml@master
